# Generated by Django 5.0.5 on 2024-05-14 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_remove_posts_apartment_remove_posts_content_and_more'),
        ('Renters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.CreateModel(
            name='Acommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('typo', models.CharField(choices=[('Apartment', 'Apartment'), ('Room', 'Room'), ('Studio', 'Studio'), ('House', 'House')], max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking_slots', models.IntegerField()),
                ('area_m2', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/media/Utility/Public/apartment_images-uploaded/')),
                ('times_rented', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
