# Generated by Django 5.0.5 on 2024-05-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
