# Generated by Django 5.0.5 on 2024-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
