# Generated by Django 5.0.3 on 2024-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='saved_posts',
        ),
        migrations.AddField(
            model_name='data',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by_users', to='Publication.posts'),
        ),
    ]
