# Generated by Django 5.0.5 on 2024-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_data_saved_posts_data_saved_posts'),
        ('Payment', '0002_remove_card_card_owner_remove_card_id_card_card_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='order_history',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sale_list',
        ),
        migrations.RemoveField(
            model_name='data',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='data',
            name='payment_info',
            field=models.ManyToManyField(related_name='users_cards', to='Payment.card'),
        ),
    ]
