# Generated by Django 5.0.5 on 2024-05-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='room',
        ),
    ]
