# Generated by Django 5.0.5 on 2024-05-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_remove_posts_apartment_remove_posts_content_and_more'),
        ('Renters', '0002_remove_room_owner_acommodation_delete_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='acommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Renters.acommodation'),
        ),
    ]
